#!/usr/bin/env bash

readonly version=0.5.0

small="
\`\`\`
  _    ___ _____ __  __
 | |  / __|_   _|  \/  |
 | |_| (_ | | | | |\/| |
 |____\___| |_| |_|  |_|
\`\`\`
"

slant="
\`\`\`
   __   _____________  ___
  / /  / ___/_  __/  |/  /
 / /__/ (_ / / / / /|_/ / 
/____/\___/ /_/ /_/  /_/  
\`\`\`
"

usage() {
  cat <<USAGE_TEXT
A simple command-line tool for copying LGTM fancy text to your clipboard.

Usage: lgtm [<option> | <argument>]

Arguments:
small   Copies small font text
slant   Copies slant font text

OPTIONS:
-h, --help        Print this usage information
-v, --version     Print the lgtm version

For bug reporting, feature requests, and contributions, please see:
https://github.com/gozeloglu/lgtm
USAGE_TEXT
}

lgtm_small() {
  echo "$small" | pbcopy
}

lgtm_slant() {
  echo "$slant" | pbcopy
}

# Default command. Copies small one. 
if (( $# == 0 )); then 
  lgtm_small
  exit
fi 

# If option or argument is passed.
if (( $# == 1 )); then
  case "$1" in
    small)
      lgtm_small
      exit
      shift
      ;;
    slant)
      lgtm_slant
      exit
      shift
      ;;
    --help | -h)
      usage
      shift
      ;;
    --version | -v)
      echo $version
      exit
      shift
      ;;
    *)
      echo "lgtm: $*: Invalid command"
      echo "See lgtm --help."
      shift
      ;;
  esac
fi
